### ISSUE TITLE
liquibaseDbDoc stage fails for postgres 11.4 version. It could work for postgres 9.5 version

### ISSUE THREAD

**Issue by gaudah** [jenkinsci/liquibase-runner-plugin#14]
Hello Team,
         I am facing one issue in liquibase-runner plugin. I tried several ways but couldn't resolve.Please help me if you know anything about this.
liquibaseUpdate and liquibaseRollback could work well but liquibaseDbDoc stage couldn't.
All these 3 stages work fine with postgres version 9.5 but not with postgres version 10 or 11.
I am using 11.4 postgres version. I have installed java,jdk & set the classpath as well.Below are the output of those.
1) echo $CLASSPATH
.:/usr/share/java/postgresql-42.2.6.jar:/usr/share/java/postgresql-42.2.6.jar
2) echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64/jre

1) Jenkins Script Is attached below
node {
stage('Checkout') {
    echo 'Checkout Code Started...'
    git url: 'https://github.com/gaudah/liquibase-git-jenkins.git', credentialsId: '30a90c33-83ea-4aaf-a196-5a256e11c60a', branch: 'development'
    echo 'Checkout Completed...'
}
 
stage('Update') {
    echo 'Updation Started...'
    liquibaseUpdate changeLogFile: 'liquibase-changelog.xml',url: 'jdbc:postgresql://localhost/postgres?user=postgres&password=iauro100&ssl=false', databaseEngine: 'PostgreSQL'
    echo 'Updation Completed...'
}

stage('Rollback') {
    echo 'Rollback Started...'
    liquibaseRollback changeLogFile: 'liquibase-changelog.xml',url: 'jdbc:postgresql://localhost/postgres?user=postgres&password=iauro100&ssl=false', databaseEngine: 'PostgreSQL', rollbackCount: 1
    echo 'Rollback Completed...'
}

stage('liquibaseDbDoc New') {
    echo 'liquibaseDbDoc New Started...'
    
    liquibaseDbDoc( changeLogFile: 'liquibase-changelog.xml',   // same basic configuration parameters
                   url: 'jdbc:postgresql://localhost/postgres?user=postgres&password=iauro100&ssl=false',
                   driverClassname: 'org.postgresql.Driver',
                   outputDirectory: 'dbdoclatestgauddoc17')
                   
                   
    /*liquibaseDbDoc( changeLogFile: 'liquibase-changelog.xml',   // same basic configuration parameters
                   url: 'jdbc:postgresql://localhost/postgres?user=postgres&password=iauro100&ssl=false',
                   classpath: ':/usr/share/java/postgresql-42.2.6.jar',
                   databaseEngine: 'PostgreSQL',
                   driverClassname: 'org.postgresql.Driver',
                   defaultSchemaName: 'public',
                   outputDirectory: 'dbdoclatestgauddoc17') */      
                   
    
    echo 'liquibaseDbDoc New Completed...'

}

2) Jenkins script logs after running jenkins script
`Started by user aishwarya
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /var/lib/jenkins/workspace/dbdoc debug
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Checkout)
[Pipeline] echo
Checkout Code Started...
[Pipeline] git
using credential 30a90c33-83ea-4aaf-a196-5a256e11c60a
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/gaudah/liquibase-git-jenkins.git # timeout=10
Fetching upstream changes from https://github.com/gaudah/liquibase-git-jenkins.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://github.com/gaudah/liquibase-git-jenkins.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/development^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/development^{commit} # timeout=10
Checking out Revision 7865ddb561742816673d16843a7fcf17df3c0130 (refs/remotes/origin/development)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 7865ddb561742816673d16843a7fcf17df3c0130
 > git branch -a -v --no-abbrev # timeout=10
 > git branch -D development # timeout=10
 > git checkout -b development 7865ddb561742816673d16843a7fcf17df3c0130
Commit message: "postgresql-42.2.6.jar added"
 > git rev-list --no-walk 7865ddb561742816673d16843a7fcf17df3c0130 # timeout=10
[Pipeline] echo
Checkout Completed...
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Update)
[Pipeline] echo
Updation Started...
[Pipeline] liquibaseUpdate
Running liquibase command 'update'
Ran changeset: json_files/accountschangelog.json::3::nvoxland
[Pipeline] echo
Updation Completed...
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Rollback)
[Pipeline] echo
Rollback Started...
[Pipeline] liquibaseRollback
Rollback back the last 1 changeset(s) applied.
json_files/accountschangelog.json::3::nvoxland: Rolled back
[Pipeline] echo
Rollback Completed...
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (liquibaseDbDoc New)
[Pipeline] echo
liquibaseDbDoc New Started...
[Pipeline] liquibaseDbDoc
Generating Liquibase dbDoc in directory 'dbdoc'
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
liquibase.exception.DatabaseException: Empty result set, expected one row
	at liquibase.util.JdbcUtils.requiredSingleResult(JdbcUtils.java:141)
	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:144)
Caused: liquibase.exception.DatabaseException: Expected single row from liquibase.statement.core.GetViewDefinitionStatement@519b8eef but got 0
	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:146)
	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:157)
	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:152)
	at liquibase.database.AbstractJdbcDatabase.getViewDefinition(AbstractJdbcDatabase.java:892)
	at liquibase.snapshot.jvm.ViewSnapshotGenerator.snapshotObject(ViewSnapshotGenerator.java:78)
Caused: liquibase.exception.DatabaseException: Error getting jdbc:postgresql://localhost:5432/postgres?user=postgres&password=iauro100 view with liquibase.statement.core.GetViewDefinitionStatement@217c08fa
	at liquibase.snapshot.jvm.ViewSnapshotGenerator.snapshotObject(ViewSnapshotGenerator.java:103)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:60)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:63)
	at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:50)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:246)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:363)
	at liquibase.snapshot.DatabaseSnapshot.replaceObject(DatabaseSnapshot.java:385)
	at liquibase.snapshot.DatabaseSnapshot.includeNestedObjects(DatabaseSnapshot.java:293)
	at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:267)
	at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:80)
	at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:53)
	at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:28)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:150)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:139)
	at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:127)
	at liquibase.changelog.visitor.DBDocVisitor.writeHTML(DBDocVisitor.java:135)
	at liquibase.Liquibase.generateDocumentation(Liquibase.java:1409)
	at org.jenkinsci.plugins.liquibase.evaluator.DatabaseDocBuilder$DatabaseDocGenerationCallback.invoke(DatabaseDocBuilder.java:71)
	at org.jenkinsci.plugins.liquibase.evaluator.DatabaseDocBuilder$DatabaseDocGenerationCallback.invoke(DatabaseDocBuilder.java:55)
	at hudson.FilePath.act(FilePath.java:1076)
	at hudson.FilePath.act(FilePath.java:1059)
	at org.jenkinsci.plugins.liquibase.evaluator.DatabaseDocBuilder.runPerform(DatabaseDocBuilder.java:52)
	at org.jenkinsci.plugins.liquibase.evaluator.AbstractLiquibaseBuilder.perform(AbstractLiquibaseBuilder.java:136)
	at org.jenkinsci.plugins.liquibase.workflow.DbDocExecution.run(DbDocExecution.java:39)
	at org.jenkinsci.plugins.liquibase.workflow.DbDocExecution.run(DbDocExecution.java:15)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:42)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:268)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:176)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor338.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:158)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:156)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:160)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:130)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:130)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
Caused: java.io.IOException: Error generating documentation
	at org.jenkinsci.plugins.liquibase.evaluator.DatabaseDocBuilder$DatabaseDocGenerationCallback.invoke(DatabaseDocBuilder.java:73)
	at org.jenkinsci.plugins.liquibase.evaluator.DatabaseDocBuilder$DatabaseDocGenerationCallback.invoke(DatabaseDocBuilder.java:55)
	at hudson.FilePath.act(FilePath.java:1076)
	at hudson.FilePath.act(FilePath.java:1059)
	at org.jenkinsci.plugins.liquibase.evaluator.DatabaseDocBuilder.runPerform(DatabaseDocBuilder.java:52)
	at org.jenkinsci.plugins.liquibase.evaluator.AbstractLiquibaseBuilder.perform(AbstractLiquibaseBuilder.java:136)
	at org.jenkinsci.plugins.liquibase.workflow.DbDocExecution.run(DbDocExecution.java:39)
	at org.jenkinsci.plugins.liquibase.workflow.DbDocExecution.run(DbDocExecution.java:15)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:42)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:268)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:176)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at sun.reflect.GeneratedMethodAccessor338.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:158)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:157)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:156)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:160)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:130)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:130)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:127)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:57)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor336.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at sun.reflect.GeneratedMethodAccessor333.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:347)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:259)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:247)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE`

**Comment by robertericreeves** [comment]
We changed the Liquibase Runner Plugin for 1.3.0 significantly. That should resolve this issue.
